---
title: "Understanding Inequalities Data Visualization with `ggplot2` Course Outline"
author: "Ben Matthews"
date: "`r Sys.Date()`"
output: github_document
---
## Outline

> “Visualizations give you answers to questions you didn’t know you had” --- Ben Shneiderman

Data visualization is a fundamental skill for quantitative social scientists, both for exploratory data analysis and communicating results effectively. This session gives an introduction to data visualization principles and application using the R package `ggplot2`.

`ggplot2` is an incredibly popular package for data visualization, used by academics, data journalists (such as BBC, New York Times and the Guardian) and citizen scientists around the world. `ggplot2` allows users to combine simple elements to create sophisticated and illuminating visualizations to better understand and tell stories with data.

The course will cover the basic facilities of `ggplot2` with hands-on-practical sessions. We will also demonstrate some of the more advanced capabilities of `ggplot2`, by introducing its mapping capabilities. By the end of this course participants will be able to create publication-ready graphics using `ggplot2`'s core functionality, will be able to use `ggplot2` as a tool for effective exploratory data analysis, and will have a foundation on which to learn `ggplot2`'s more advanced functions.

Participants should have basic familiarity with the `R` statistical programming language.


## Learning outcomes

1.	Basic principles of data visualization
2.	Basic usage of `ggplot2` (scatterplots, bar plots, fitted lines)
3.	Basic principles of mapping
4.	Basic used of `ggplot2` for mapping





## Program

### Session One: Principles of data visualization

09:00-10:00

### Session Two: Introduction to `ggplot2`

10:00-11:00 lecture
11:00-12:30 practical

### Lunch

12:30-13:30

### Session Three: Introduction to mapping

13:30-14:00

### Session Four: Maps practical

14:00-16:30

### Session Five: Review (and advanced ggplot)

16:30-17:00

## Course texts

- Data Visualization: A practical introduction - Kieran Healy https://socviz.co/ _This is more about the how to do I think_
- Fundamentals of Data Visualization- Claus O. Wilke https://serialmentor.com/dataviz/ _And this about the what to do_
- R for Data Science (Chapter 3) - Hadley Wickham and Garret Grolemund https://r4ds.had.co.nz/data-visualisation.html
- Data visualisation with `ggplot2` YouTube playlist - Danielle Navarro https://www.youtube.com/playlist?list=PLRPB0ZzEYegPa4uvvAVJnr6loSKbN4wLb

### Other texts

- Geocomputation with R - Robin Lovelace, Jakub Nowosad, Jannes Muenchow https://geocompr.robinlovelace.net/
- Maps maps maps - Danielle Navarro https://djnavarro.net/post/maps/
- Spruce up your ggplot2 visualizations with formatted text - Claus Wilke https://www.slideshare.net/ClausWilke/spruce-up-your-ggplot2-visualizations-with-formatted-text
- The Glamour of Graphics - Will Chase https://www.williamrchase.com/slides/assets/player/KeynoteDHTMLPlayer.html#0

### Just for fun

- See It with Figures - John Levi Martin (Review of Data Visualization: A Practical Introduction) https://journals.sagepub.com/doi/full/10.1177/0094306119880195
